### ISSUE TITLE
ModuleNotFoundError: No Module named 'flask'

### ISSUE THREAD

**Issue by HyperTNT** [kevinjycui/DesmosBezierRenderer#19]
I can't figure out why it is not working. I have uninstalled and installed the requirements folder but it still does not work. i think it cant find any module because all the external module have yellow underlines. Also i am very new to python and html.

**Comment by SamTheDog0** [comment]
Hi. I could only install all the dependencies using a linux os (I used lubuntu on virtualbox). In your case, try:
pip3 install flask

Also - because I used a VM (virtual machine) I didn't worry about the virtual environment (using pyenv), and just installed everything locally.

___ Some Steps ____
1. git clone "https://github.com/kevinjycui/DesmosBezierRenderer.git" 
2. cd DesmosBezierRenderer
3. Make your frames folder and add an image (see instructions on main site) [make sure the image is a small one - otherwise the browser will likely crash or take ages]
4. pip3 install -r requirements.txt
5. python3 backend.py
6. open the .html file in a browser (I found chromium worked faster than firefox)
7. Move the slidy thing to one and after a while the image should appear or the frame download....

**Comment by HyperTNT** [comment]
The problem occurs when I run the 
python3 backend.py
I did every step before correctly and it still fails. Should I just get a virtualbox or something else.

**Comment by SamTheDog0** [comment]
What Operating System are you using? - If linux (eg ubuntu/linux mint etc....) then it should be fine. 
If not linux - download virtual box and follow an online guide to install a linux distro (eg. lubuntu)

If you have python installed you should be able to run: 
python3 install flask
And it should install flask. To check then run
python3 -m flask
If that works  (aka it doesn't say no module named flask) - you have flask and something else is the problem.

Another suggestion is to include the '3' on python3 - otherwise you could be using python2.

I could only get all the modules to install using virtualbox - so I'd suggest using that.....

You could also try:
sudo apt install python3-flask
or
sudo apt install flask-python3

**Comment by HyperTNT** [comment]
Um, so I just got this line
python3: can't open file 'install': [Errno 2] No such file or directory
What does this mean

**Comment by HyperTNT** [comment]
I got it to work once and now I used a different filetype after changing the FILE_EXT it doesn't work. I don't even know how it worked in the first place.
